---
title: "Presentations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---



## 2025

---

Toronto Climate Economics Meeting, organized by Jeffrey Sun and Stephan Heiblich.

Inaugural Climate Finance Conference, UM6P, organized by UBC's Ali Lazrak and Bilal Islah. [Slides](https://www.dropbox.com/scl/fi/r7zfk6q8wyoy86swuh8fp/slides.pdf?rlkey=pi6h64h5qh0yqpqdbjv6uqmvc&dl=0)

Urban Economics Meeting, Rotman School of Business, organized by William Strange. [Slides](https://www.dropbox.com/scl/fi/3pgtxrz05gej7zcj2l9oa/slides.pdf?rlkey=3f45e3l2bqhvu7htjt2wl58fs&dl=0)

Panelist at the Federal Reserve of Chicago, "The Impact of Public and Private Funding Availability Following a Natural Disaster," with Daniel Hartley, Kristen Broady, Ben Keys, Ralf Meisenzahl. Wednesday, March 5, 2025.

<iframe src='https://players.brightcove.net/4934638106001/Sk7cO8ZDB_default/index.html?videoId=6369648226112' 
        width="800" 
        height="450" 
        allowfullscreen 
        frameborder=0>
</iframe>

Urban Economics Association, Berlin. [Slides](https://www.dropbox.com/scl/fi/u97fenhum1k57bgxjknp9/presentation.pdf?rlkey=fr8frnr33g5uztu5wn2g1wlhe&dl=0)

American Finance Association, San Francisco. [Slides](https://www.dropbox.com/scl/fi/r7zfk6q8wyoy86swuh8fp/slides.pdf?rlkey=pi6h64h5qh0yqpqdbjv6uqmvc&dl=0)

Econometric Society, San Francisco. [Slides](https://www.dropbox.com/scl/fi/3pgtxrz05gej7zcj2l9oa/slides.pdf?rlkey=3f45e3l2bqhvu7htjt2wl58fs&dl=0)

American Real Estate and Urban Economics Association.

## 2024

---

FHFA Econ Summit, Washington DC, November.

Annual meeting of the Urban Economics Association, Washington DC, September.

UC Riverside Workshop on Energy and the Climate Transition, September.

Freddie Mac (Federal Home Loan Mortgage Corporation), June, Washington DC.

NYU Stern Climate Finance Conference, May 31st, New York City.

American Real Estate and Urban Economics Association, National Meeting, Washington DC.

University of Wisconsin-Madison.

Discussions and chair: 2x American Economic Association. Association of Environmental and Resource Economists and American Real Estate and Urban Economics Association.

---

## 2023

---

Virtual Seminar on Climate Economics, organized by Federal Reserve of San Francisco.

Bloomberg LP, Manhattan.

Bank of Canada conference.

US Treasury, Office of Financial Research.

Freddie Mac.

Federal Reserve of New York (invited seminar).

National Meeting of the American Real Estate and Urban Economics Association.

Office of the Comptroller of the Currency.

Canadian Economics Association.

University of Pennsylvania, Wharton School of Business (invited seminar).

Temple University, Fox School of Business, Philadelphia (invited seminar).

Eastern Finance Association.

Office of the Superintendent of Financial Institutions, Canada.

___

## 2022

---

Keynote Lecture on Climate Risk in Real Estate at the Massachusetts Institute of Technology, Cambridge, MA.

Federal Reserve Board, Divisions of Research & Statistics and Monetary Affairs, Climate and Economic Activity group, Washington DC.

Bank of Canada, attended by the Governor and the Governing Council, Ottawa. 

Urban Economics Association, Washington DC.

Mortgage Market Research Conference, Federal Reserve of Philadelphia, Discussant.

Rutgers Business School, New Jersey.

[Macrohistory Lab Webinar](https://www.macrohistory.net/seminars/), University of Bonn.

Federal Reserve Bank of New York.

Zicklin School of Business at Baruch College.

___

## 2021

___


NYU Stern PhD Finance Class.

Discussant at the Online Spatial & Urban Seminar (OSUS).

Carlson School of Management at the University of Minnesota.

American Real Estate and Urban Economics Association (AREUEA) Seminar.

International meeting of the AREUEA (discussant).

European Meeting of the Urban Economics Association.

American Economic Association, Annual Meeting.

___

## 2020

___

Winter Finance Conference, Whistler, University of British Columbia.

Federal Reserve of Philadelphia.

American Enterprise Institute.

Cambridge University – Department of Land Economics – Real Estate Seminar.

___

## 2019

___

NBER Summer Institute – Real Estate Group.

Urban Economics Association (Annual Meeting) – Federal Reserve of Philadelphia.

McGill University.

University of Alberta.

___

## 2018

___

University of Ottawa.

Petralia Political Economy Conference.

Econometric Society (Annual Meeting) at University of California, Davis.

International Association for Applied Econometrics, IAAE, Annual Meeting.

Institute for New Economic Thinking conference organized by Hashem Pesaran.

University of Laval. 

---

## 2017

---

University of Montreal, Department of Economics.

University of Toronto, Department of Economics.

University of Southern California, Marshall School of Business.

NBER ISOM meeting, Vilnius.

[Vrij Universiteit (VU University)](http://www.feweb.vu.nl/en/), Amsterdam.

[Bruegel European Think Tank](http://bruegel.org/), Assessing Macroeconomic Impacts using Micro Data, a panel with Richard Blundell and Helmut Kraemer.

[University of Southern California, Economics department, Dornsife College of Letters, Arts, and Science](http://dornsife.usc.edu/econ/), Los Angeles.

[Kraksfond Workshop on City Structure](http://kraksfondbyforskning.dk/en/2016/12/04/workshop-city-structure/), Copenhagen, Denmark.

___

## 2016

---

World Bank, Development Research Group, Washington D.C.

HEC Montreal.

Urban Economics Association annual conference, Minneapolis.

University of Pennsylvania, Wharton School of Business, CURE meeting, September.

Ecole Polytechnique, Palaiseau.

New York University, joint seminar in NYC with NYU Stern's Urbanization Project, NYU's Furman Center for Real Estate, and the Marron Institute for Urban Management.

___

## 2015

---

London School of Economics, “Job Displacement and Crime”.

Board of Governors of the Federal Reserve, July 2015. [Slides](https://www.dropbox.com/s/8oba02vjzi9xh6a/board-of-governors.pdf?dl=0)

Attending by invitation NBER Summer Institute 2015.

International Monetary Fund, Washington DC, Credit Standards and Segregation. [Slides](https://www.dropbox.com/s/8oba02vjzi9xh6a/board-of-governors.pdf?dl=0)

___

## 2014

---

NBER Political Economy group, organized by Alberto Alesina. April meeting.

New York University, Economics seminar, Abu Dhabi campus.

___

## 2013

---

Georgetown Business School, Center for Business and Public Policy.

Maxwell School, Syracuse University, New York.

Duke University, Economics department.

Federal Reserve Bank of Philadelphia.

IESE Business School, Barcelona.

University of Hamburg

___

## 2012

---

Urban Economics Conference, Ottawa, Canada.
“Real Estate Brokers and the Dynamics of Segregation” Slides

Econometric Society, 66th European Meeting, Malaga, Spain.
“Credit Standards and Segregation”

Rimini Conference in Economics and Finance, University of Toronto, Canada
“Credit Standards and Segregation”

North American Summer Meeting of the Econometric Society, Evanston, IL.

The American Real Estate and Urban Economics Association meeting, Washington D.C.
“Credit Standards and Segregation”

Paris School of Economics, Labor Economics and Public Policy Seminar.
“Students’ Perceptions of Teacher Biases: Experimental Economics in Schools.”

GREQAM, Marseille.
“Credit Standards and Segregation” . Slides

Joint INSEAD-Georgetown Conference
“Foreclosures and Segregation”

Université Catholique de Louvain La Neuve
“Using Compulsory Mobility to Estimate Pupil Effects, Peer Effects, and School Quality.”

___

## 2011

---

Sciences Po Workshop on Discrimination and Segregation (with Kevin Lang, Leah Boustan, David Neumark, Patrick Bayer)
“Credit Standards and Segregation” Slides

Miami, Florida, Urban Economics Association (UEA) meeting at the 58th Annual North American Meetings of the Regional Science Association International (RSAI)
“Credit Standards and Segregation”. Slides

London School of Economics, Labor Seminar, June.
“The Effect of Credit Standards on Urban and School Segregation”. Slides

CEPR Public Policy Symposium, Zurich, May.
“The Effect of Credit Standards on Urban and School Segregation”. Slides

Society of Labor Economists, Annual Meeting, Vancouver, British Columbia, 
“The Effect of Credit Standards on Urban and School Segregation”. Slides

Georgetown Business and Public Policy Conference, Washington D.C,
“Estimating Perceptions of Discrimination: Experimental Economics in Schools”

CORE, Université Catholique de Louvain, Belgium,
“Blockbusting: Brokers and the Dynamics of Segregation”.

Copenhagen Business School, Denmark,
“Estimating Perceptions of Discrimination: Experimental Economics in Schools”.

___

## 2010

---

Tinbergen Institute, Amsterdam,
“The Effect of Credit Standards on Urban and School Segregation”. 

CREST-INSEE, Paris,
“Blockbusting: Brokers and the Dynamics of Segregation.”

University of Michigan, Ford School of Public Policy,
“The Effect of Credit Standards on Urban and School Segregation.”

Public Economics Conference, Journees Louis-Andre Gerard-Varet, Marseille,
“Blockbusting: Brokers and the Dynamics of Segregation.”

University of Texas, Austin, Economics Department,
“Estimating Perceptions of Discrimination: Experimental Economics in Schools.”

___

## 2009

---

Sciences Po Economics Department,
“Blockbusting: Brokers and the Dynamics of Segregation.”

___

## 2008

---

U.S. National Academy of Science Meeting,
“Social Interactions in Economics.”

<iframe src="https://player.vimeo.com/video/33252644" width="500" height="375" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/33252644">Social Interaction - Amine Ouazad, INSEAD</a> from <a href="https://vimeo.com/kfos">Kavli Frontiers of Science</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

Society of Labor Economists Meeting, Columbia University,
“Using Compulsory Mobility to Estimate Pupil Effects, Peer Effects, and School Quality.”

New York University, Steinhardt School,
“Assessed by a Teacher Like Me: Race, Gender, and Subjective Evaluations.”

INSEAD Economics Department,
“Assessed by a Teacher Like Me: Race, Gender, and Subjective Evaluations.”

University of Michigan, Ford School of Public Policy,
“Assessed by a Teacher Like Me: Race, Gender, and Subjective Evaluations.”

Meeting of the Centre for Economic Performance, London School of Economics,
“Blockbusting: Brokers and the Dynamics of Segregation.”

___

## 2007

---

Boston College, Economics Department,
“Using Compulsory Mobility to Estimate Pupil Effects, Peer Effects, and School Quality.”

Cornell University, Economics Department,
“Using Compulsory Mobility to Estimate Pupil Effects, Peer Effects, and School Quality.”

Princeton University, Industrial Relations Section,
“Assessed by a Teacher Like Me: Race, Gender, and Subjective Evaluations.”

Université Catholique de Louvain-La-Neuve, CORE.

___

## 2006

---

European Institute, Florence.

CEPR Meeting, Economics of Education and Education Policy in Europe, Uppsala.

___

## 2005

---

Workshop on Social Interactions with Charles Manski, Uppsala University, Sweden.

University of Bonn.
